const fs = require("fs");
const path = "server.js";
let c = fs.readFileSync(path, "utf8");
const old = "} else if (rewardType === \x27frame\x27 && rewardBoosterName) {\r\n              const ownedRowPass = db.prepare(\x27SELECT owned_items FROM users WHERE id = ?\x27).get(wsUser.id);\r\n              let ownedItemsPass = {};\r\n              if (ownedRowPass && ownedRowPass.owned_items) { try { ownedItemsPass = JSON.parse(ownedRowPass.owned_items); } catch (e) {} }\r\n              ownedItemsPass[rewardBoosterName] = true;\r\n              db.prepare(\x27UPDATE users SET owned_items = ? WHERE id = ?\x27).run(JSON.stringify(ownedItemsPass), wsUser.id);\r\n            }";
const idx = c.indexOf(old);
console.log("Tapildi:", idx !== -1);
if (idx !== -1) {
  const replacement = "} else if (rewardType === \x27frame\x27 && rewardBoosterName) {\r\n              const ownedRowPass = db.prepare(\x27SELECT owned_items FROM users WHERE id = ?\x27).get(wsUser.id);\r\n              let ownedItemsPass = {};\r\n              if (ownedRowPass && ownedRowPass.owned_items) { try { ownedItemsPass = JSON.parse(ownedRowPass.owned_items); } catch (e) {} }\r\n              ownedItemsPass[rewardBoosterName] = true;\r\n              db.prepare(\x27UPDATE users SET owned_items = ? WHERE id = ?\x27).run(JSON.stringify(ownedItemsPass), wsUser.id);\r\n            } else if (rewardType === \x27booster\x27 && rewardBoostersJson) {\r\n              const ownedRowBst = db.prepare(\x27SELECT owned_items FROM users WHERE id = ?\x27).get(wsUser.id);\r\n              let ownedItemsBst = {};\r\n              if (ownedRowBst && ownedRowBst.owned_items) { try { ownedItemsBst = JSON.parse(ownedRowBst.owned_items); } catch (e) {} }\r\n              try {\r\n                const boosterList = JSON.parse(rewardBoostersJson);\r\n                boosterList.forEach(bItem => {\r\n                  const bId = bItem.id; const bCount = Number(bItem.count) || 1;\r\n                  ownedItemsBst[bId] = (Number(ownedItemsBst[bId]) || 0) + bCount;\r\n                });\r\n              } catch (e) { console.log(\x27WS: booster json parse xetasi - \x27 + e.message); }\r\n              db.prepare(\x27UPDATE users SET owned_items = ? WHERE id = ?\x27).run(JSON.stringify(ownedItemsBst), wsUser.id);\r\n            } else if (rewardType === \x27boosters_multi\x27 && rewardBoostersJson) {\r\n              const ownedRowBm = db.prepare(\x27SELECT owned_items FROM users WHERE id = ?\x27).get(wsUser.id);\r\n              let ownedItemsBm = {};\r\n              if (ownedRowBm && ownedRowBm.owned_items) { try { ownedItemsBm = JSON.parse(ownedRowBm.owned_items); } catch (e) {} }\r\n              try {\r\n                const idList = JSON.parse(rewardBoostersJson);\r\n                idList.forEach(bId => {\r\n                  ownedItemsBm[bId] = (Number(ownedItemsBm[bId]) || 0) + 1;\r\n                });\r\n              } catch (e) { console.log(\x27WS: boosters_multi json parse xetasi - \x27 + e.message); }\r\n              db.prepare(\x27UPDATE users SET owned_items = ? WHERE id = ?\x27).run(JSON.stringify(ownedItemsBm), wsUser.id);\r\n            }";
  c = c.replace(old, replacement);
  fs.writeFileSync(path, c, "utf8");
  console.log("YAZILDI");
}
