const fs = require("fs");
const path = "server.js";
let c = fs.readFileSync(path, "utf8");
const old = "if (category !== \x27total_kisses\x27) {\r\n            const topUsersNonKiss = db.prepare(\x27SELECT * FROM users ORDER BY CAST(\x27 + sortCol + \x27 AS INTEGER) DESC LIMIT 50\x27).all();\r\n            if (category === \x27gestures\x27) console.log(\x27WS: DEBUG period gestures - period=\x27 + period + \x27 - \x27 + JSON.stringify(topUsersNonKiss.slice(0,3).map(function(u){return {name:u.username, gestures_sent:u.gestures_sent};})));\r\n            return topUsersNonKiss.map(function(u, idx) {\r\n              return { id: String(u.id), male: u.gender !== \x27female\x27, name: u.display_name || u.username, photo_url: u.avatar_data ? (\x27/api/avatar/\x27 + u.id) : \x27\x27, total_kisses: u.total_kisses, points: u.points, price: u.price_stat || 0, harem_price: u.harem_price_stat || 0, dj_score: u.points, gestures: u.gestures_sent || 0, rank: idx + 1 };\r\n            });\r\n          }";
const idx = c.indexOf(old);
console.log("Tapildi:", idx !== -1);
if (idx !== -1) {
  const replacement = "const transactionTypeMap = { total_kisses: \x27total_kisses_period\x27, dj_score: \x27dj_score_period\x27, harem_price: \x27price_period\x27, gestures: \x27gestures_period\x27 };\r\n          const txType = transactionTypeMap[category];\r\n          if (category !== \x27total_kisses\x27 && !txType) {\r\n            const topUsersSnapshot = db.prepare(\x27SELECT * FROM users ORDER BY CAST(\x27 + sortCol + \x27 AS INTEGER) DESC LIMIT 50\x27).all();\r\n            return topUsersSnapshot.map(function(u, idx) {\r\n              return { id: String(u.id), male: u.gender !== \x27female\x27, name: u.display_name || u.username, photo_url: u.avatar_data ? (\x27/api/avatar/\x27 + u.id) : \x27\x27, total_kisses: u.total_kisses, points: u.points, price: u.harem_price_stat || 0, harem_price: u.price_stat || 0, dj_score: u.points, gestures: u.gestures_sent || 0, rank: idx + 1 };\r\n            });\r\n          }\r\n          if (category !== \x27total_kisses\x27) {\r\n            const periodStartX = getPeriodStart(period);\r\n            const rowsX = db.prepare(\r\n              \x27SELECT user_id, SUM(amount) as cnt FROM transactions WHERE type = ? AND created_at >= ? GROUP BY user_id ORDER BY cnt DESC LIMIT 50\x27\r\n            ).all(txType, periodStartX);\r\n            return rowsX.map(function(r, idx) {\r\n              const u = db.prepare(\x27SELECT * FROM users WHERE id = ?\x27).get(r.user_id);\r\n              if (!u) return null;\r\n              const result = { id: String(u.id), male: u.gender !== \x27female\x27, name: u.display_name || u.username, photo_url: u.avatar_data ? (\x27/api/avatar/\x27 + u.id) : \x27\x27, total_kisses: u.total_kisses, points: u.points, price: u.harem_price_stat || 0, harem_price: u.price_stat || 0, dj_score: u.points, gestures: u.gestures_sent || 0, rank: idx + 1 };\r\n              if (category === \x27dj_score\x27) result.dj_score = r.cnt;\r\n              if (category === \x27harem_price\x27) result.harem_price = r.cnt;\r\n              if (category === \x27gestures\x27) result.gestures = r.cnt;\r\n              return result;\r\n            }).filter(function(x) { return x !== null; });\r\n          }";
  c = c.replace(old, replacement);
  fs.writeFileSync(path, c, "utf8");
  console.log("YAZILDI");
}
